version: '3.8'

services:
  backend:
    build: ./backend
    container_name: node_app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_app
    working_dir: /app
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

